# Generated by Django 4.2.13 on 2024-05-30 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('contrato_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(null=True)),
                ('vigente', models.BooleanField()),
                ('contenido', models.TextField()),
                ('contratista', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratacionesEmpleado', to='Sistema.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratosEmpresa', to='Sistema.empresa')),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contratoEmpresaDetalle', to='GestionContratos.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratosEmpleado', to='Sistema.empleado')),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contratoEmpleadoDetalle', to='GestionContratos.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoArrendamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratosArrendamiento', to='Sistema.empresa')),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contratoArrendamientoDetalle', to='GestionContratos.contrato')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratosArrendamiento', to='Sistema.local')),
            ],
        ),
    ]
