# Generated by Django 4.2.13 on 2024-05-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionContratos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='contrato_id',
            new_name='contratoId',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='fecha_fin',
            new_name='fechaFin',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='fecha_inicio',
            new_name='fechaInicio',
        ),
    ]
