# Generated by Django 4.2.13 on 2024-05-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionContratos', '0002_rename_contrato_id_contrato_contratoid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoarrendamiento',
            name='tipo',
            field=models.CharField(default='Arrendamiento', max_length=20),
        ),
        migrations.AddField(
            model_name='contratoempleado',
            name='tipo',
            field=models.CharField(default='Empleado', max_length=20),
        ),
        migrations.AddField(
            model_name='contratoempresa',
            name='tipo',
            field=models.CharField(default='Empresa', max_length=20),
        ),
    ]
