# Generated by Django 4.2.13 on 2024-05-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionContratos', '0003_contratoarrendamiento_tipo_contratoempleado_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoarrendamiento',
            name='tipo',
            field=models.CharField(default='Arrendamiento', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='contratoempleado',
            name='tipo',
            field=models.CharField(default='Empleado', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='contratoempresa',
            name='tipo',
            field=models.CharField(default='Empresa', editable=False, max_length=20),
        ),
    ]
