# Generated by Django 4.2.13 on 2024-06-01 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0010_remove_empleado_respondeeconomicamentepor_and_more'),
        ('GestionContratos', '0004_alter_contratoarrendamiento_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoarrendamiento',
            name='contratante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratosArrendamiento', to='Sistema.empresa'),
        ),
        migrations.AlterField(
            model_name='contratoempresa',
            name='contratante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratosEmpresa', to='Sistema.empresa'),
        ),
    ]
