# Generated by Django 4.2.13 on 2024-06-01 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0010_remove_empleado_respondeeconomicamentepor_and_more'),
        ('GestionContratos', '0005_alter_contratoarrendamiento_contratante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoempleado',
            name='contratante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratosEmpleado', to='Sistema.empleado'),
        ),
    ]
