# Generated by Django 4.2.13 on 2024-06-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionContratos', '0007_contrato_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='archivo',
        ),
        migrations.AddField(
            model_name='contrato',
            name='archivo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
