# Generated by Django 4.2.13 on 2024-06-02 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionContratos', '0008_remove_contrato_archivo_contrato_archivo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='archivo_url',
            new_name='archivo',
        ),
    ]
