# Generated by Django 4.2.13 on 2024-06-02 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionContratos', '0010_rename_contratista_contrato_contratador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='vigente',
            new_name='aprobado',
        ),
    ]
