# Generated by Django 4.2.13 on 2024-05-30 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sistema', '0002_empleado_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='respondeEconomicamentePor',
            field=models.ManyToManyField(blank=True, null=True, related_name='responsableEconomico', to='Sistema.persona'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
