# Generated by Django 4.2.13 on 2024-05-30 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0003_alter_empleado_respondeeconomicamentepor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(default='empresa por defecto', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='local',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Sistema.empresa'),
        ),
    ]
