# Generated by Django 4.2.13 on 2024-05-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0004_empresa_nombre_alter_local_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
