# Generated by Django 4.2.13 on 2024-05-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0005_local_disponible_alter_local_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='empresa_id',
            new_name='empresaId',
        ),
    ]
