# Generated by Django 4.2.13 on 2024-05-30 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0006_rename_empresa_id_empresa_empresaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='local',
            name='nombre',
        ),
    ]
