# Generated by Django 4.2.13 on 2024-06-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0009_alter_empleado_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='respondeEconomicamentePor',
        ),
        migrations.AddField(
            model_name='empleado',
            name='informacionAdicional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
