# Generated by Django 4.2.13 on 2024-06-01 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0010_remove_empleado_respondeeconomicamentepor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='local',
            name='estado',
        ),
    ]
